# Generated by Django 5.0 on 2023-12-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='logo',
            new_name='icon',
        ),
    ]
