# Generated by Django 5.0.1 on 2024-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_rename_logo_chatbot_icon'),
        ('knowledgebases', '0005_alter_knowledgebase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='knowledgebases',
            field=models.ManyToManyField(to='knowledgebases.knowledgebase'),
        ),
    ]
