# Generated by Django 5.0.1 on 2024-02-05 10:23

import chatbots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0004_alter_chatbot_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='icon',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=chatbots.models.upload_icon),
        ),
    ]
