FROM python:3.11.7
WORKDIR /app
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN apt update
RUN apt install libreoffice -y
COPY . .
RUN chmod +x ./worker-entrypoint.sh

ENTRYPOINT [ "./worker-entrypoint.sh" ]
