# Generated by Django 5.0 on 2024-01-10 15:21

import knowledgebases.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('file/text', 'Text'), ('file/pdf', 'PDF'), ('file/docx', 'Word Document'), ('file/csv', 'CSV'), ('file/markdown', 'Markdown'), ('file/json', 'JSON'), ('content/webpage', 'Webpage'), ('content/sitemap', 'Sitemap')], max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to=knowledgebases.models.upload_file)),
                ('content_url', models.URLField(max_length=1000)),
                ('vectorized', models.BooleanField(default=False)),
            ],
        ),
    ]
