# Generated by Django 5.0.1 on 2024-01-11 18:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0002_remove_knowledgebase_vectorized_knowledgebase_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chroma_id', models.UUIDField()),
                ('text', models.TextField()),
                ('knowledgebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledgebases.knowledgebase')),
            ],
        ),
    ]
