# Generated by Django 5.0.1 on 2024-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0003_knowledgebasedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='content_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
