# Generated by Django 5.0.1 on 2024-02-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0006_alter_knowledgebase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
