# Generated by Django 5.0.1 on 2024-02-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0007_alter_knowledgebasedocument_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebasedocument',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
