# Generated by Django 5.0.1 on 2024-02-05 10:22

import knowledgebases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0008_alter_knowledgebasedocument_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=knowledgebases.models.upload_file),
        ),
    ]
