# Generated by Django 5.0.1 on 2024-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebases', '0009_alter_knowledgebase_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='type',
            field=models.CharField(choices=[('file/text', 'Text'), ('file/pdf', 'PDF'), ('file/docx', 'Microsoft Word'), ('file/pptx', 'Microsoft PowerPoint'), ('file/markdown', 'Markdown'), ('content/webpage', 'Webpage'), ('content/website', 'Website')], max_length=200),
        ),
    ]
